export const uiText = {
  app: {
    title: 'Automation Engine Admin',
    shell: {
      railAriaLabel: 'Global navigation rail',
      panelAriaLabel: 'Section panel',
      contentAriaLabel: 'Workspace content',
      inspectorAriaLabel: 'Inspector region',
      panelTitle: 'Workspace Panel',
      inspectorTitle: 'Inspector',
      inspectorFallback: 'Inspector content will appear here when a route publishes detail context.',
      openPanel: 'Open panel',
      closePanel: 'Close panel',
      openInspector: 'Open inspector',
      closeInspector: 'Close inspector',
    },
    nav: {
      ariaLabel: 'Primary',
      webhooks: 'Webhooks',
      processedCalls: 'Processed Calls',
    },
  },
  session: {
    disabledMessage: 'Session guard is enabled and admin UI access is currently disabled.',
    disabledPanelNote: 'Enable admin UI access to restore full workspace controls.',
  },
  webhooks: {
    title: 'Webhooks',
    subtitle: 'Webhook event operations workspace.',
    inspectorTitle: 'Webhook Inspector',
    inspectorDescription: 'Selected webhook details and payload metadata will appear here.',
    historyEndpointLabel: 'History endpoint',
    detailEndpointLabel: 'Detail endpoint',
    liveStreamEndpointLabel: 'Live stream endpoint',
    previewFieldHeader: 'Field',
    previewValueHeader: 'Value',
    streamTitle: 'Live Stream Events',
    streamStateLabel: 'Connection state',
    streamEmptyMessage: 'Waiting for webhook stream events.',
    streamIdHeader: 'ID',
    streamEventTypeHeader: 'Event Type',
    streamStatusHeader: 'Status',
    streamSourceHeader: 'Source',
    streamReceivedAtHeader: 'Received At',
  },
  processedCalls: {
    title: 'Processed Calls',
    subtitle: 'Review processed call outcomes and replay activity.',
    inspectorTitle: 'Replay Inspector',
    inspectorDescription: 'Replay selection details and action outcomes will appear here.',
    callIdHeader: 'Call ID',
    outcomeHeader: 'Outcome',
    replayStatusHeader: 'Replay Status',
    processedAtHeader: 'Processed At',
    emptyMessage: 'No processed calls available yet.',
  },
  states: {
    loadingTitle: 'Loading',
    loadingMessage: 'Please wait while data is being prepared.',
    emptyTitle: 'No results found',
    emptyMessage: 'Adjust filters or try again later.',
    errorTitle: 'Something went wrong',
    errorMessage: 'An unexpected error occurred. Please try again.',
    retry: 'Retry',
  },
  filters: {
    apply: 'Apply',
    reset: 'Reset',
  },
  dialog: {
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  notifications: {
    close: 'Dismiss notification',
    successTitle: 'Success',
    errorTitle: 'Error',
    warningTitle: 'Warning',
    infoTitle: 'Info',
  },
} as const
