export const uiText = {
  app: {
    title: 'Automation Engine Admin',
    shell: {
      railAriaLabel: 'Global navigation rail',
      panelAriaLabel: 'Section panel',
      contentAriaLabel: 'Workspace content',
      inspectorAriaLabel: 'Inspector region',
      panelTitle: 'Workspace Panel',
      inspectorTitle: 'Inspector',
      inspectorFallback: 'Inspector content will appear here when a route publishes detail context.',
      openPanel: 'Open panel',
      closePanel: 'Close panel',
      openInspector: 'Open inspector',
      closeInspector: 'Close inspector',
    },
    nav: {
      ariaLabel: 'Primary',
      home: 'Go to landing page',
      webhooks: 'Webhooks',
      processedCalls: 'Processed Calls',
      workflows: 'Workflows',
      workflowRuns: 'Workflow Runs',
    },
  },
  session: {
    disabledMessage: 'Session guard is enabled and admin UI access is currently disabled.',
    disabledPanelNote: 'Enable admin UI access to restore full workspace controls.',
  },
  landing: {
    kicker: 'AUTOMATION ENGINE',
    title: 'From call outcome to follow-up task — automated, auditable, reliable.',
    subtitle: 'Five stages. One pipeline. Every call outcome routed to the right action with a full audit trail.',
    workspaceAriaLabel: 'Landing workspace overview',
    timelineAriaLabel: 'Story timeline milestones',
    timelinePathAriaLabel: 'Horizontal swirling milestone path',
    footerNote: 'Scenario 1 is live: outcome → task automation. Coming next: intent classification and transcription analysis.',
    primaryAction: 'Open Dashboard',
    secondaryAction: 'View Webhooks',
    milestoneTagPrefix: 'Milestone',
    milestones: {
      oneTitle: 'Webhook Ingest',
      oneBody: 'Signed webhook events arrive and are persisted with full payload integrity.',
      twoTitle: 'Outcome Decision',
      twoBody: 'Call outcomes are matched to deterministic rules that define the next action.',
      threeTitle: 'Task Execution',
      threeBody: 'Follow-up tasks are created and tracked with end-to-end status visibility.',
      fourTitle: 'Replay Recovery',
      fourBody: 'Failed events replay safely, preserving a complete and queryable audit trail.',
      fiveTitle: 'Scale Next',
      fiveBody: 'Intent classification and transcription analysis join the pipeline next.',
    },
  },
  webhooks: {
    title: 'Webhooks',
    subtitle: 'Webhook event operations workspace.',
    inspectorTitle: 'Webhook Inspector',
    inspectorDescription: 'Selected webhook details and payload metadata appear here.',
    tableTitle: 'Webhook History',
    filterSourceLabel: 'Source',
    filterStatusLabel: 'Status',
    filterEventTypeLabel: 'Event Type',
    filterFromLabel: 'From',
    filterToLabel: 'To',
    filterSourceAll: 'All sources',
    filterStatusAll: 'All statuses',
    filterEventTypeAll: 'All event types',
    filterDatePlaceholder: 'Pick date',
    tableEventIdHeader: 'Event ID',
    tableSourceHeader: 'Source',
    tableEventTypeHeader: 'Event Type',
    tableStatusHeader: 'Status',
    tableReceivedAtHeader: 'Received At',
    tableEmptyMessage: 'No webhook events found for the selected filters.',
    rowAriaLabelPrefix: 'Select webhook event',
    paginationNext: 'Next',
    paginationNextAria: 'Load next page',
    paginationNoMore: 'No more results',
    inspectorEmpty: 'Select a webhook row to load event detail.',
    inspectorLoading: 'Loading webhook detail...',
    inspectorError: 'Unable to load webhook detail.',
    inspectorDetailTitle: 'Webhook Event Detail',
    detailIdLabel: 'ID',
    detailEventIdLabel: 'Event ID',
    detailSourceLabel: 'Source',
    detailEventTypeLabel: 'Event Type',
    detailStatusLabel: 'Status',
    detailPayloadHashLabel: 'Payload Hash',
    detailPayloadLabel: 'Payload',
    detailReceivedAtLabel: 'Received At',
    viewLatest: 'View latest',
    viewLatestAria: 'View latest webhook events',
    liveStateConnecting: 'Connecting',
    liveStateLive: 'Live',
    liveStateError: 'Reconnecting/Error',
    liveStatePaused: 'Paused',
    pauseStreamAria: 'Pause webhook live stream',
    resumeStreamAria: 'Resume webhook live stream',
    heartbeatLabel: 'Last heartbeat',
    missingEventId: 'N/A',
  },
  processedCalls: {
    title: 'Processed Calls',
    subtitle: 'Review processed call outcomes and replay activity.',
    inspectorTitle: 'Replay Inspector',
    inspectorDescription: 'Replay selection details and action outcomes will appear here.',
    tableTitle: 'Processed Calls History',
    filterStatusLabel: 'Status',
    filterFromLabel: 'From',
    filterToLabel: 'To',
    filterStatusAll: 'All statuses',
    callIdHeader: 'Call ID',
    statusHeader: 'Status',
    ruleAppliedHeader: 'Rule Applied',
    taskIdHeader: 'Task ID',
    failureReasonHeader: 'Failure Reason',
    retryCountHeader: 'Retry Count',
    updatedAtHeader: 'Updated At',
    replayHeader: 'Replay',
    rowAriaLabelPrefix: 'Select processed call',
    replayAriaPrefix: 'Replay processed call',
    replayTooltip: 'Replay failed call',
    replayDisabledTooltip: 'Replay is available only for FAILED calls',
    replayConfirmTitle: 'Confirm Replay',
    replayConfirmDescription: 'This will replay the selected FAILED call and re-run automation.',
    replayConfirmAction: 'Replay',
    replayAcceptedMessage: 'Replay accepted',
    replayNotFoundMessage: 'Processed call not found.',
    replayNotReplayableMessage: 'Replay is allowed only for FAILED calls.',
    replayUnexpectedErrorMessage: 'Unable to replay processed call.',
    inspectorEmpty: 'Select a processed call row to view context.',
    inspectorSelectedTitle: 'Selected Call',
    inspectorReplayOutcomeTitle: 'Last Replay Outcome',
    inspectorNotReplayable: 'Replay unavailable for non-FAILED status.',
    emptyMessage: 'No processed calls available yet.',
  },
  workflows: {
    title: 'Workflows',
    subtitle: 'Read-only workflow management surface (Phase 2.1 foundation).',
    subtitleCreate: 'Workflow management workspace with create flow (Phase 2.2).',
    panelTitle: 'Workflow Catalog',
    inspectorTitle: 'Workflow Inspector',
    inspectorDescription: 'Select a workflow row to preview quick details.',
    stepTypesTitle: 'Step Types',
    triggerTypesTitle: 'Trigger Types',
    tableTitle: 'Workflow Definitions',
    tableEmptyMessage: 'No workflows found for the selected filters.',
    filterStatusLabel: 'Status',
    filterStatusAll: 'All statuses',
    keyHeader: 'Key',
    nameHeader: 'Name',
    statusHeader: 'Status',
    versionHeader: 'Version',
    createdHeader: 'Created',
    rowAriaLabelPrefix: 'Open workflow',
    detailTitle: 'Workflow Detail',
    detailSubtitle: 'Workflow definition and lifecycle controls.',
    detailNotFound: 'Workflow not found.',
    detailMetadataTitle: 'Metadata',
    detailTriggerTitle: 'Trigger',
    detailGraphTitle: 'Graph',
    detailActionsTitle: 'Actions',
    detailTabDefinition: 'Definition',
    detailTabStoryboard: 'Storyboard',
    detailTabRuns: 'Runs',
    detailBreadcrumbSeparator: '›',
    detailTriggerMetaPrefix: 'trigger',
    detailVersionMetaPrefix: 'v',
    detailGraphInvalidTitle: 'Invalid graph',
    detailGraphInvalidMessage: 'This workflow has a definition that does not match the current runtime schema.',
    storyboardValidationIdleHint: 'Click Validate to check this definition.',
    storyboardValidationValidLabel: 'Definition is valid',
    storyboardValidationInvalidLabel: 'Definition has validation issues',
    storyboardValidationPendingLabel: 'Validating definition…',
    storyboardValidationErrorLabel: 'Validation request failed',
    storyboardValidationIssuesCount: (count: number) => `${count} issue${count === 1 ? '' : 's'}`,
    storyboardValidationShowIssues: 'Show issues',
    storyboardValidationHideIssues: 'Hide issues',
    storyboardValidationRetry: 'Retry',
    storyboardValidateCta: 'Validate',
    sceneInspectorTitle: 'Step inspector',
    sceneInspectorCloseLabel: 'Close inspector',
    sceneInspectorTypeLabel: 'Type',
    sceneInspectorIdLabel: 'ID',
    sceneInspectorConfigLabel: 'Config',
    sceneInspectorTransitionsLabel: 'Transitions',
    sceneInspectorEmptyConfig: 'No configuration',
    sceneInspectorEmptyTransitions: 'No declared transitions',
    sceneInspectorTransitionTerminal: 'terminal',
    sceneInspectorNotFound: 'Selected step not found in this graph.',
    detailRunsTitle: 'Workflow Runs',
    detailRunsEmptyMessage: 'No workflow runs found for this workflow and filters.',
    detailRunsFilterStatusLabel: 'Run Status',
    detailRunsFilterStatusAll: 'All run statuses',
    detailRunIdHeader: 'Run ID',
    detailRunStatusHeader: 'Status',
    detailRunReasonCodeHeader: 'Reason Code',
    detailRunStartedHeader: 'Started',
    detailRunCompletedHeader: 'Completed',
    detailRunRowAriaPrefix: 'Open workflow run',
    detailVersionsTitle: 'Version History',
    detailKeyLabel: 'Key',
    detailNameLabel: 'Name',
    detailDescriptionLabel: 'Description',
    detailStatusLabel: 'Status',
    detailVersionLabel: 'Version',
    detailCreatedLabel: 'Created',
    inspectorEmpty: 'Select a workflow from the list to preview details.',
    createdAtUnknown: 'N/A',
    createButton: 'Create Workflow',
    createSuccess: 'Workflow created successfully.',
    createError: 'Unable to create workflow.',
    create: {
      title: 'Create Workflow',
      description: 'Provide workflow metadata and JSON definitions for trigger and graph.',
      keyLabel: 'Key',
      keyPlaceholder: 'lead_follow_up_v1',
      keyRequired: 'Workflow key is required.',
      nameLabel: 'Name',
      namePlaceholder: 'Lead follow-up workflow',
      nameRequired: 'Workflow name is required.',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Optional description',
      statusLabel: 'Status',
      triggerJsonLabel: 'Trigger JSON',
      graphJsonLabel: 'Graph JSON',
      invalidJson: 'Invalid JSON.',
      jsonObjectRequired: 'JSON object is required.',
      submit: 'Create',
      submitting: 'Creating...',
    },
    editSuccess: 'Workflow updated successfully.',
    editError: 'Unable to update workflow.',
    validateSuccess: 'Workflow definition is valid.',
    validateInvalid: 'Workflow definition has validation errors.',
    validateError: 'Unable to validate workflow.',
    activateSuccess: 'Workflow activated.',
    activateError: 'Unable to activate workflow.',
    deactivateSuccess: 'Workflow deactivated.',
    deactivateError: 'Unable to deactivate workflow.',
    archiveSuccess: 'Workflow archived.',
    archiveError: 'Unable to archive workflow.',
    rollbackSuccess: 'Workflow rolled back successfully.',
    rollbackError: 'Unable to rollback workflow.',
    rollbackConfirmTitle: 'Confirm Rollback',
    rollbackConfirmDescription: 'This will rollback workflow definition to the selected version.',
    validationResultTitle: 'Validation Result',
    validationPendingTitle: 'Validation In Progress',
    validationPendingMessage: 'Validating workflow definition against trigger and graph constraints.',
    validationValidLabel: 'Valid',
    validationInvalidLabel: 'Invalid',
    validationErrorsTitle: 'Validation Errors',
    validationDismiss: 'Dismiss Validation',
    edit: {
      title: 'Edit Workflow',
      description: 'Update workflow metadata and JSON definitions.',
      nameLabel: 'Name',
      nameRequired: 'Workflow name is required.',
      descriptionLabel: 'Description',
      triggerJsonLabel: 'Trigger JSON',
      graphJsonLabel: 'Graph JSON',
      invalidJson: 'Invalid JSON.',
      jsonObjectRequired: 'JSON object is required.',
      submit: 'Save Changes',
      submitting: 'Saving...',
    },
    actions: {
      edit: 'Edit',
      validate: 'Validate',
      activate: 'Activate',
      deactivate: 'Deactivate',
      archive: 'Archive',
      rollback: 'Rollback',
      activateConfirmTitle: 'Confirm Activate',
      activateConfirmDescription: 'This will activate the current workflow version.',
      deactivateConfirmTitle: 'Confirm Deactivate',
      deactivateConfirmDescription: 'This will deactivate the current workflow version.',
      archiveConfirmTitle: 'Confirm Archive',
      archiveConfirmDescription: 'This will archive the workflow and remove it from active use.',
    },
  },
  workflowRuns: {
    title: 'Workflow Runs',
    subtitle: 'Read-only global workflow run observability surface.',
    tableTitle: 'Workflow Runs',
    tableEmptyMessage: 'No workflow runs found for the selected filters.',
    inspectorTitle: 'Run Inspector',
    inspectorEmpty: 'Select a workflow run row to preview quick details.',
    filterStatusLabel: 'Status',
    filterStatusAll: 'All statuses',
    runIdHeader: 'Run ID',
    workflowKeyHeader: 'Workflow Key',
    versionHeader: 'Version',
    statusHeader: 'Status',
    reasonCodeHeader: 'Reason Code',
    startedAtHeader: 'Started',
    completedAtHeader: 'Completed',
    rowAriaLabelPrefix: 'Open workflow run',
    panelTitle: 'Runs Summary',
    panelShownCountLabel: 'Shown',
    panelFailedCountLabel: 'Failed',
    detailTitle: 'Workflow Run Detail',
    detailSubtitle: 'Read-only workflow run inspection surface.',
    detailBackLabel: 'Back to Runs',
    detailNotFound: 'Workflow run not found.',
    detailMetadataTitle: 'Metadata',
    detailTriggerPayloadTitle: 'Trigger Payload',
    detailStepsTitle: 'Steps',
    cancelAction: 'Cancel Run',
    cancelConfirmTitle: 'Confirm Run Cancel',
    cancelConfirmDescription: 'This will cancel this workflow run. Pending and blocked steps will be skipped.',
    cancelSuccess: 'Workflow run canceled.',
    cancelError: 'Unable to cancel workflow run.',
    detailRunIdLabel: 'Run ID',
    detailWorkflowKeyLabel: 'Workflow Key',
    detailVersionLabel: 'Version',
    detailStatusLabel: 'Status',
    detailReasonCodeLabel: 'Reason Code',
    detailStartedAtLabel: 'Started At',
    detailCompletedAtLabel: 'Completed At',
    detailSourceLeadIdLabel: 'Source Lead ID',
    detailEventIdLabel: 'Event ID',
    missingValue: 'N/A',
    missingReasonCode: 'None',
    stepNodeIdLabel: 'Node',
    stepTypeLabel: 'Step Type',
    stepStatusLabel: 'Status',
    stepResultCodeLabel: 'Result',
    stepRetryCountLabel: 'Retries',
    stepDueAtLabel: 'Due',
    stepStartedAtLabel: 'Started',
    stepCompletedAtLabel: 'Completed',
    stepDetailsToggle: 'Step details',
    stepOutputsLabel: 'Outputs',
    stepErrorLabel: 'Error',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Live view of active workflows, run health, and inbound webhook activity.',
    panelTitle: 'Pipeline Summary',
    inspectorTitle: 'Dashboard Inspector',
    inspectorDescription: 'High-level pipeline health — active definitions, run outcomes, and recent webhook ingestion.',
    activeWorkflowsTitle: 'Active Workflows',
    recentRunsTitle: 'Recent Runs',
    failedRunsTitle: 'Failed Runs',
    systemHealthTitle: 'Ingest Activity',
    openWorkflows: 'Browse Workflows',
    openRuns: 'Browse All Runs',
    openFailedRuns: 'Browse Failed Runs',
    recentRunsEmpty: 'No recent workflow runs found.',
    failedRunsEmpty: 'No failed workflow runs found.',
    runIdHeader: 'Run ID',
    workflowKeyHeader: 'Workflow Key',
    statusHeader: 'Status',
    completedAtHeader: 'Completed',
    activeWorkflowsCountLabel: 'Count',
    failedRunsCountLabel: 'Count',
    recentWebhooksLabel: 'Recent Webhooks',
    latestWebhookAtLabel: 'Latest Webhook',
    placeholderHealthMessage: 'Detailed call-to-task accountability metrics are on the roadmap.',
    statActiveWorkflowsLabel: 'active definitions',
    statFailedRunsLabel: 'failed runs',
    statWebhookEventsLabel: 'recent webhook events',
    allClearMessage: 'No failed runs — pipeline is healthy.',
    latestIngestLabel: 'Last ingest',
    viewIngestActivity: 'View Webhook Activity',
  },
  states: {
    loadingTitle: 'Loading',
    loadingMessage: 'Please wait while data is being prepared.',
    emptyTitle: 'No results found',
    emptyMessage: 'Adjust filters or try again later.',
    errorTitle: 'Something went wrong',
    errorMessage: 'An unexpected error occurred. Please try again.',
    retry: 'Retry',
  },
  common: {
    paginationPrevious: 'Previous',
    paginationNext: 'Next',
    jsonCopy: 'Copy',
    jsonCopied: 'Copied',
  },
  filters: {
    apply: 'Apply',
    reset: 'Reset',
  },
  dialog: {
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  notifications: {
    close: 'Dismiss notification',
    successTitle: 'Success',
    errorTitle: 'Error',
    warningTitle: 'Warning',
    infoTitle: 'Info',
  },
} as const
