export const uiText = {
  app: {
    title: 'Automation Engine Admin',
    shell: {
      railAriaLabel: 'Global navigation rail',
      panelAriaLabel: 'Section panel',
      contentAriaLabel: 'Workspace content',
      inspectorAriaLabel: 'Inspector region',
      panelTitle: 'Workspace Panel',
      inspectorTitle: 'Inspector',
      inspectorFallback: 'Inspector content will appear here when a route publishes detail context.',
      openPanel: 'Open panel',
      closePanel: 'Close panel',
      openInspector: 'Open inspector',
      closeInspector: 'Close inspector',
    },
    nav: {
      ariaLabel: 'Primary',
      home: 'Go to landing page',
      webhooks: 'Webhooks',
      processedCalls: 'Processed Calls',
      policies: 'Policies',
    },
  },
  session: {
    disabledMessage: 'Session guard is enabled and admin UI access is currently disabled.',
    disabledPanelNote: 'Enable admin UI access to restore full workspace controls.',
  },
  landing: {
    kicker: 'AUTOMATION ENGINE',
    title: 'A clean horizontal story of how a call becomes a follow-up task.',
    subtitle: 'One left-to-right journey with milestone cards. Built to sit inside one screen height.',
    workspaceAriaLabel: 'Landing workspace overview',
    timelineAriaLabel: 'Story timeline milestones',
    timelinePathAriaLabel: 'Horizontal swirling milestone path',
    footerNote: 'Now shipping: Scenario 1 (outcome to task). Next storyline: intent + transcription.',
    primaryAction: 'Open Webhooks',
    secondaryAction: 'Open Processed Calls',
    milestoneTagPrefix: 'Milestone',
    milestones: {
      oneTitle: 'Webhook Ingest',
      oneBody: 'Receive signed events and persist them safely.',
      twoTitle: 'Outcome Decision',
      twoBody: 'Map call outcomes to deterministic task intent.',
      threeTitle: 'Task Execution',
      threeBody: 'Create follow-up tasks with clear status traceability.',
      fourTitle: 'Replay Recovery',
      fourBody: 'Replay failures while preserving audit context.',
      fiveTitle: 'Scale Next',
      fiveBody: 'Extend into intent + transcription automation.',
    },
  },
  webhooks: {
    title: 'Webhooks',
    subtitle: 'Webhook event operations workspace.',
    inspectorTitle: 'Webhook Inspector',
    inspectorDescription: 'Selected webhook details and payload metadata appear here.',
    tableTitle: 'Webhook History',
    filterSourceLabel: 'Source',
    filterStatusLabel: 'Status',
    filterEventTypeLabel: 'Event Type',
    filterFromLabel: 'From',
    filterToLabel: 'To',
    filterSourceAll: 'All sources',
    filterStatusAll: 'All statuses',
    filterEventTypePlaceholder: 'Event type',
    filterDatePlaceholder: 'Pick date',
    tableEventIdHeader: 'Event ID',
    tableSourceHeader: 'Source',
    tableEventTypeHeader: 'Event Type',
    tableStatusHeader: 'Status',
    tableReceivedAtHeader: 'Received At',
    tableEmptyMessage: 'No webhook events found for the selected filters.',
    rowAriaLabelPrefix: 'Select webhook event',
    paginationNext: 'Next',
    paginationNextAria: 'Load next page',
    paginationNoMore: 'No more results',
    inspectorEmpty: 'Select a webhook row to load event detail.',
    inspectorLoading: 'Loading webhook detail...',
    inspectorError: 'Unable to load webhook detail.',
    inspectorDetailTitle: 'Webhook Event Detail',
    detailIdLabel: 'ID',
    detailEventIdLabel: 'Event ID',
    detailSourceLabel: 'Source',
    detailEventTypeLabel: 'Event Type',
    detailStatusLabel: 'Status',
    detailPayloadHashLabel: 'Payload Hash',
    detailPayloadLabel: 'Payload',
    detailReceivedAtLabel: 'Received At',
    viewLatest: 'View latest',
    viewLatestAria: 'View latest webhook events',
    liveStateConnecting: 'Connecting',
    liveStateLive: 'Live',
    liveStateError: 'Reconnecting/Error',
    liveStatePaused: 'Paused',
    pauseStreamAria: 'Pause webhook live stream',
    resumeStreamAria: 'Resume webhook live stream',
    heartbeatLabel: 'Last heartbeat',
    missingEventId: 'N/A',
  },
  processedCalls: {
    title: 'Processed Calls',
    subtitle: 'Review processed call outcomes and replay activity.',
    inspectorTitle: 'Replay Inspector',
    inspectorDescription: 'Replay selection details and action outcomes will appear here.',
    tableTitle: 'Processed Calls History',
    filterStatusLabel: 'Status',
    filterFromLabel: 'From',
    filterToLabel: 'To',
    filterStatusAll: 'All statuses',
    callIdHeader: 'Call ID',
    statusHeader: 'Status',
    ruleAppliedHeader: 'Rule Applied',
    taskIdHeader: 'Task ID',
    failureReasonHeader: 'Failure Reason',
    retryCountHeader: 'Retry Count',
    updatedAtHeader: 'Updated At',
    replayHeader: 'Replay',
    rowAriaLabelPrefix: 'Select processed call',
    replayAriaPrefix: 'Replay processed call',
    replayTooltip: 'Replay failed call',
    replayDisabledTooltip: 'Replay is available only for FAILED calls',
    replayConfirmTitle: 'Confirm Replay',
    replayConfirmDescription: 'This will replay the selected FAILED call and re-run automation.',
    replayConfirmAction: 'Replay',
    replayAcceptedMessage: 'Replay accepted',
    replayNotFoundMessage: 'Processed call not found.',
    replayNotReplayableMessage: 'Replay is allowed only for FAILED calls.',
    replayUnexpectedErrorMessage: 'Unable to replay processed call.',
    inspectorEmpty: 'Select a processed call row to view context.',
    inspectorSelectedTitle: 'Selected Call',
    inspectorReplayOutcomeTitle: 'Last Replay Outcome',
    inspectorNotReplayable: 'Replay unavailable for non-FAILED status.',
    emptyMessage: 'No processed calls available yet.',
  },
  policies: {
    title: 'Policies',
    subtitle: 'Policy management and execution monitoring.',
    tabRuns: 'Runs',
    tabManage: 'Manage',
    panelTitle: 'Filters',
    inspectorTitle: 'Policy Inspector',
    // Runs tab
    runsTableTitle: 'Execution Runs',
    runsIdHeader: 'ID',
    runsLeadHeader: 'Lead',
    runsPolicyHeader: 'Policy',
    runsStatusHeader: 'Status',
    runsWhenHeader: 'When',
    runsEmptyMessage: 'No execution runs found. Runs appear here when leads trigger active policies.',
    runsRowAriaPrefix: 'Select execution run',
    // Run inspector
    runInspectorTitle: 'Execution Detail',
    runStatusLabel: 'Status',
    runReasonCodeLabel: 'Outcome',
    runLeadLabel: 'Lead',
    runPolicyLabel: 'Policy',
    runSourceLabel: 'Source',
    runEventIdLabel: 'Event ID',
    runCreatedAtLabel: 'Created',
    runStepsTitle: 'Step Timeline',
    // Run statuses
    runStatusPending: 'Pending',
    runStatusBlockedPolicy: 'Blocked',
    runStatusDuplicateIgnored: 'Duplicate',
    runStatusCompleted: 'Completed',
    runStatusFailed: 'Failed',
    // Step statuses
    stepStatusPending: 'Pending',
    stepStatusWaitingDependency: 'Waiting',
    stepStatusProcessing: 'Processing',
    stepStatusCompleted: 'Completed',
    stepStatusFailed: 'Failed',
    stepStatusSkipped: 'Skipped',
    // Step types
    stepTypeCheckClaim: 'Check Claim',
    stepTypeCheckComms: 'Check Communication',
    stepTypeExecuteAction: 'Execute Action',
    // Manage tab
    manageTableTitle: 'Policy Versions',
    managePolicyKeyHeader: 'Policy Key',
    manageVersionHeader: 'Version',
    manageStatusHeader: 'Status',
    manageEnabledHeader: 'Enabled',
    manageEmptyMessage: 'No policies created yet.',
    managePolicyRowAriaPrefix: 'Select policy',
    // Policy inspector
    policyInspectorTitle: 'Policy Detail',
    policyDomainLabel: 'Domain',
    policyKeyLabel: 'Policy Key',
    policyStatusLabel: 'Status',
    policyVersionLabel: 'Version',
    policyEnabledLabel: 'Enabled',
    policyBlueprintTitle: 'Blueprint',
    policyStatusActive: 'Active',
    policyStatusInactive: 'Inactive',
    // Actions
    actionReassign: 'Reassign to User',
    actionMoveToPond: 'Move to Pond',
    // Filters
    filterPolicyLabel: 'Policy',
    filterPolicyAll: 'All policies',
    filterStatusLabel: 'Status',
    filterStatusAll: 'All statuses',
    filterDomainLabel: 'Domain',
    filterDomainAll: 'All domains',
    filterFromLabel: 'From',
    filterToLabel: 'To',
    // Summary
    summaryActivePolicies: 'Active policies',
    summaryRunsShown: 'Runs shown',
    summaryFailed: 'Failed',
    // Inspector empty
    inspectorEmpty: 'Select a row to view details.',
    inspectorEmptyRuns: 'Select an execution run to view step details.',
    inspectorEmptyManage: 'Select a policy to view its configuration.',
    inspectorLoading: 'Loading details...',
    inspectorError: 'Unable to load details.',
    // Pagination
    paginationNext: 'Next',
    paginationPrev: 'Previous',
    paginationNoMore: 'No more results',
    // Nav
    navLabel: 'Policies',
  },
  states: {
    loadingTitle: 'Loading',
    loadingMessage: 'Please wait while data is being prepared.',
    emptyTitle: 'No results found',
    emptyMessage: 'Adjust filters or try again later.',
    errorTitle: 'Something went wrong',
    errorMessage: 'An unexpected error occurred. Please try again.',
    retry: 'Retry',
  },
  filters: {
    apply: 'Apply',
    reset: 'Reset',
  },
  dialog: {
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  notifications: {
    close: 'Dismiss notification',
    successTitle: 'Success',
    errorTitle: 'Error',
    warningTitle: 'Warning',
    infoTitle: 'Info',
  },
} as const
